[Variables]

;Large Launcher Buttons====================

LLT=A
;Program Name
LLP=C:\Users\Alienware\AppData\Local\Google\Chrome\Application\chrome.exe
;Program Path
LLI=C:\Users\Nischal\Documents\Rainmeter\Skins\Avengers\Large Launchers/A.png
;Program Icon

LLT2=Opera
LLP2=C:\Program Files (x86)\Opera\opera.exe
LLI2=C:\Users\Nischal\Documents\Rainmeter\Skins\Avengers\Large Launchers/B.png

LLT3=Internet Explorer
LLP3=C:\Program Files (x86)\Internet Explorer\iexplore.exe
LLI3=C:\Users\Nischal\Documents\Rainmeter\Skins\Avengers\Large Launchers/C.png

LLT4=Safari
LLP4=C:\Program Files (x86)\Safari\Safari.exe
LLI4=C:\Users\Nischal\Documents\Rainmeter\Skins\Avengers\Large Launchers/M.png

LLT5=Firefox
LLP5=C:\Program Files (x86)\Mozilla Firefox\firefox.exe
LLI5=C:\Users\Nischal\Documents\Rainmeter\Skins\Avengers\Large Launchers/mp3skull.png

LLT6=Thunderbird
LLP6=C:\Program Files (x86)\Mozilla Thunderbird\thunderbird.exe
LLI6=C:\Users\Nischal\Documents\Rainmeter\Skins\Avengers\Large Launchers/pandora.png

;Small Launcher Buttons===========================

SLT1=Photoshop
SLP1=C:\Program Files\Adobe\Adobe Photoshop CS5.1 (64 Bit)\Photoshop.exe
SLI1=#SKINSPATH#\Avengers\Small Launchers\Photoshop2.png

SLT2=Illustrator
SLP2=C:\Program Files (x86)\Adobe\Adobe Illustrator CS5.1\Support Files\Contents\Windows\Illustrator.exe
SLI2=#SKINSPATH#\Avengers\Small Launchers\Illustrator.png

SLT3=Premiere Pro
SLP3=C:\Program Files\Adobe\Adobe Premiere Pro CS5.5\Adobe Premiere Pro.exe
SLI3=#SKINSPATH#\Avengers\Small Launchers\Premiere.png

SLT4=After Effects
SLP4=C:\Program Files\Adobe\Adobe After Effects CS5.5\Support Files\AfterFX.exe
SLI4=#SKINSPATH#\Avengers\Small Launchers\AfterEffects.png

SLT5=Audition
SLP5=C:\Program Files (x86)\Adobe\Adobe Audition CS5.5\Adobe Audition.exe
SLI5=#SKINSPATH#\Avengers\Small Launchers\Audition.png

SLT6=MediaEncoder
SLP6=C:\Program Files\Adobe\Adobe Media Encoder CS5.5\Adobe Media Encoder.exe
SLI6=#SKINSPATH#\Avengers\Small Launchers\MediaEncoder.png

SLT7=Dreamweaver
SLP7=C:\Program Files (x86)\Adobe\Adobe Dreamweaver CS5.5\Dreamweaver.exe
SLI7=#SKINSPATH#\Avengers\Small Launchers\Dreamweaver.png

SLT8=SoundBooth
SLP8=C:\Program Files (x86)\Adobe\Adobe Soundbooth CS5\Adobe Soundbooth CS5.exe
SLI8=#SKINSPATH#\Avengers\Small Launchers\Soundbooth.png

SLT9=Flash
SLP9=C:\Program Files (x86)\Adobe\Adobe Flash CS5.5\Adobe Flash.exe
SLI9=#SKINSPATH#\Avengers\Small Launchers\Flash.png

SLT10=Encore
SLP10=C:\Program Files (x86)\Adobe\Adobe Encore CS5.1\Adobe Encore.exe
SLI10=#SKINSPATH#\Avengers\Small Launchers\Encore.png

SLT11=Fireworks
SLP11=C:\Program Files (x86)\Adobe\Adobe Fireworks CS5.1\Fireworks.exe
SLI11=#SKINSPATH#\Avengers\Small Launchers\Fireworks.png

SLT12=InDesign
SLP12=C:\Program Files (x86)\Adobe\Adobe InDesign CS5.5\InDesign.exe
SLI12=#SKINSPATH#\Avengers\Small Launchers\InDesign.png

SLT13=Contribute
SLP13=C:\Program Files (x86)\Adobe\Adobe Contribute CS5.1\App\Contribute.exe
SLI13=#SKINSPATH#\Avengers\Small Launchers\Contribute.png

SLT14=OnLocation
SLP14=C:\Program Files (x86)\Adobe\Adobe OnLocation CS5.1\Adobe OnLocation.exe
SLI14=#SKINSPATH#\Avengers\Small Launchers\OnLocation.png

;Folder Launcher BUttons=========================

FLP1=%UserProfile%\Downloads
;Folder Path
FLN1=Downloads
;Folder Name

FLP2=%UserProfile%\Dropbox
FLN2=Dropbox

FLP3=%UserProfile%\Music
FLN3=Music

FLP4=#SKINSPATH#
FLN4=Rainmeter

FLP5=%UserProfile%\Videos
FLN5=Videos

FLP6=%UserProfile%\Pictures
FLN6=Pictures

FLP7=%UserProfile%\Documents
FLN7=Documents

;Clock Webpages==============================

WN=Facebook
;Webpage Name
WA=https:\\Facebook.com\edreyes
;Webpage Address

WN2=Twitter
WA2=http:\\twitter.com\edreyes

WN3=Youtube
WA3=http:\\youtube.com\edreyes2010

WN4=Web Forum
WA4=http:\\the.wf
WN5=Google Apps
WA5=https:\\www.google.com\a\cpanel\creativenewmediainc.com\CPanelHome#CPanelHome

WN6=Intuit
WA6=https:\\www.intuit.com\login\?content=qboContent

;Misc======================

player=itunes
Drive= C:


